/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Window Button
 #	author : miyako
 #	2017/06/08
 #
 # --------------------------------------------------------------------------------*/



// --- Window Button
void WINDOW_SET_ENABLED(sLONG_PTR *pResult, PackagePtr pParams);
void WINDOW_Get_enabled(sLONG_PTR *pResult, PackagePtr pParams);
